FROM nginx

COPY Conf /etc/nginx

COPY html /usr/share/nginx/html
COPY styles /usr/share/nginx/html/styles
COPY scripts /usr/share/nginx/html/scripts
COPY images /usr/share/nginx/html/images
EXPOSE 80
