FROM nginx

COPY Conf /etc/nginx

COPY html /usr/share/nginx/html
COPY html/styles /usr/share/nginx/html/styles
COPY html/scripts /usr/share/nginx/html/scripts
COPY html/images /usr/share/nginx/html/images
EXPOSE 80
